/**
 * generate-version.js
 *
 * Generates src/generated/version.ts from the latest Git tag using
 * `git describe --tags --always --dirty`.
 *
 * Output format examples:
 *   v2.23.0.0               — exactly on a tagged commit
 *   v2.23.0.0-3-gabc1234    — 3 commits after the tag
 *   v2.23.0.0-3-gabc1234-dirty — uncommitted changes present
 *
 * Falls back to "dev" when Git is unavailable (e.g. npm tarball install).
 *
 * Vercel shallow clones:
 *   Vercel clones repos with --depth=1 by default, which strips tags and
 *   history that `git describe` needs. This script detects that scenario
 *   and runs `git fetch --tags --unshallow` (or `--deepen`) to recover
 *   the tag metadata before retrying.
 *
 * This script runs automatically before `next dev` and `next build`
 * via the predev / prebuild npm scripts in package.json.
 * The generated file should NEVER be committed — it is listed in .gitignore.
 *
 * Cross-platform: uses only Node.js built-ins (no shell-specific syntax).
 */

const { execSync } = require("child_process");
const fs = require("fs");
const path = require("path");

/**
 * Helper: run a shell command silently and return trimmed stdout, or null on failure.
 */
function run(cmd) {
    try {
        return execSync(cmd, {
            encoding: "utf-8",
            stdio: ["pipe", "pipe", "pipe"],
        }).trim();
    } catch {
        return null;
    }
}

// ---------------------------------------------------------------------------
// 1. Resolve the version string from Git
// ---------------------------------------------------------------------------
let version = "dev";

// First attempt — works locally and in full-clone CI environments
let described = run("git describe --tags --always --dirty");

if (described && !described.match(/^[0-9a-f]+$/)) {
    // `git describe` returned a tag-based version (not a bare commit hash)
    version = described;
} else {
    // Likely a shallow clone (Vercel, GitHub Actions with depth=1, etc.)
    // Try to fetch tags and unshallow so `git describe` can find them.
    console.log("[generate-version] tag not found — attempting to fetch tags...");

    // Unshallow if this is a shallow clone (safe to call even if not shallow)
    run("git fetch --tags --unshallow") ??
        // Some CI environments use --depth instead of --shallow — deepen as fallback
        run("git fetch --tags --deepen=1000");

    // Retry after fetching tags
    described = run("git describe --tags --always --dirty");

    if (described && !described.match(/^[0-9a-f]+$/)) {
        version = described;
    } else {
        console.warn(
            "[generate-version] git describe still failed after fetch — using fallback 'dev'"
        );
    }
}

// ---------------------------------------------------------------------------
// 2. Ensure the output directory exists
// ---------------------------------------------------------------------------
const outDir = path.join(__dirname, "..", "src", "generated");
fs.mkdirSync(outDir, { recursive: true });

// ---------------------------------------------------------------------------
// 3. Write the generated TypeScript file
// ---------------------------------------------------------------------------
const outFile = path.join(outDir, "version.ts");
const content = `// AUTO-GENERATED by scripts/generate-version.js — do NOT edit manually.
// Re-generated on every \`npm run dev\` and \`npm run build\`.
export const APP_VERSION = ${JSON.stringify(version)};
`;

// Only write when the content actually changed to avoid unnecessary HMR reloads
const existing = fs.existsSync(outFile)
    ? fs.readFileSync(outFile, "utf-8")
    : "";
if (existing !== content) {
    fs.writeFileSync(outFile, content, "utf-8");
    console.log(`[generate-version] ${version} → ${outFile}`);
} else {
    console.log(`[generate-version] ${version} (unchanged)`);
}
